### PR TITLE
Fix example in readme

### PR DESCRIPTION
**Pull request by Bluscream**
Your example would not work because active would always be true, no matter if it contains "Yes" or "No" because it's a non-empty string. Didn't you test it or smth? xD

### CODE REVIEW

**Comment by Bluscream** [comment]
tbh i would even put that directly in the print statement if i were you

```py
from adguardhome import AdGuardHome

import asyncio


async def main(loop):
    """Show example how to get status of your AdGuard Home instance."""
    async with AdGuardHome("127.0.0.1", port=80, loop=loop, username="admin", password="buffalo911") as adgu$
        version = await adguard.version()
        print("AdGuard version:", version)

        active = await adguard.protection_enabled()
        print("Protection enabled?", "Yes" if active else "No")

        if not active:
            print("AdGuard Home protection disabled. Enabling...")
            await adguard.enable_protection()


if __name__ == "__main__":
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main(loop))
```

**Comment by Bluscream** [comment]
You read my pr? ^^

**Comment by frenck** [comment]
I think you need to learn some Python basics.

image


Closing PR.

**Comment by Bluscream** [comment]
You realize thats just pseudocode? the pr contains the actual code...

**Comment by frenck** [comment]
Do you realize that the code I typed it the current code to show you that it works?

**Comment by Bluscream** [comment]
It didnt work when i tried it

**Comment by frenck** [comment]
Let me make it more exact
image

**Comment by Bluscream** [comment]
Maybe it needs a special windows version?

**Comment by frenck** [comment]
This is not platform-specific. Besides, I run all unit tests (99% coverage) against Linux, Mac & Windows. Furthermore, this library is used by Home Assistant. I'm pretty sure it would have been raised already 😉

**Pull request closed without merging**
