### PR TITLE
Allow package to interact with the /blocked_services/ endpoint

### PR DESCRIPTION
**Pull request by sandervankasteel**
# Proposed Changes

AdGuardHome has functionality to completely block one or more services. For example, completely block all traffic to Facebook, WhatsApp and/or Netflix. 

These changes allow this package to interact with those endpoints. 

### Screenshot of the functionality in the webinterface of Adguard Home:
image

## Related Issues

> ([Github link][autolink-references] to related issues or pull requests)

[autolink-references]: https://help.github.com/articles/autolinked-references-and-urls/

### CODE REVIEW

**Comment by sandervankasteel** [comment]
Hi @frenck the `deepsource.io / DeepSource: Python` Github action step is failing, but when I apply the changes that step wants and then run the pre-commit hook again (`poetry run pre-commit run --all-files`). It reverts all the changes back. 

What do you want me to do with this?

**Comment by frenck** [comment]
ignore it

**Comment by sandervankasteel** [comment]
Then this PR ready for your review @frenck, if you want to accept this new feature in your library :)

**Comment by frenck** [comment]
@sandervankasteel Yes, I'm aware... that is what PRs do/are.

**Pull request closed without merging**
