### PR TITLE
Fix enabling parental controls

### PR DESCRIPTION
**Pull request by hastarin**
…nt-type application/json is allowed` #795

# Proposed Changes

Detailed in #795 

## Related Issues

> ([Github link][autolink-references] to related issues or pull requests)

[autolink-references]: https://help.github.com/articles/autolinked-references-and-urls/

### CODE REVIEW

**Comment by hastarin** [comment]
@frenck would you be able to check and merge this?

**Comment by frenck** [comment]
Sorry I am traveling at this moment (and the upcoming weeks).

**Comment by hastarin** [comment]
No worries enjoy the travel.

**Comment by hastarin** [comment]
@frenck are you back from travelling to take a look at this?

**Review by frenck — CHANGES_REQUESTED** [review]
Both formatting CI & units tests are failing.

Please make sure CI passes.

../Frenck

**Review by frenck — APPROVED** [review]
Thanks, @hastarin 👍 

../Frenck

**Comment by hastarin** [comment]
@frenck Sorry I just noticed the failed check for pylint. Hopefully this fixes it but will have to wait for your approval to see the workflow run to be sure.

**Review by frenck — APPROVED** [review]
Thanks, @hastarin 👍

**Pull request merged**
